### PR TITLE
Bind arguments are now shown in a query

### PR DESCRIPTION
**Pull request by dobrodushny**
Please, let me now, if it is needed to add more specs. Thanks!

### CODE REVIEW

**Comment by nepalez** [comment]
Hi! Yes, I think specs should check what error messages are provided for various cases.

I'd also like to point out to [this comment](https://github.com/nepalez/rspec-sqlimit/pull/3#issuecomment-303708494). Today I'm not sure that inserting bindings into query was a good decision, its better to display them separately like Rails does.

**Comment by dobrodushny** [comment]
Hi! I've seen that comment and the output format is like you've described there. If I'm wrong, plz correct me.

**Comment by nepalez** [comment]
Ahh, yes, you're right.

I'm ok with a code. Still I think you should test that bindings are displayed. It's fine that you've created additional specs, but they cover main functionality (that matcher works per se  ;) ), but not error messages

**Comment by dobrodushny** [comment]
Yeah, agreed with you :) Some specs are added for reporter class

**Comment by dobrodushny** [comment]
@nepalez could you please give some updates on pr status? Maybe something is required or it's ok in it's current state. Thanks!

**Comment by nepalez** [comment]
Hi! Ahh, sorry, I've missed the change ))

**Comment by nepalez** [comment]
@Dobrodushny  Thank you!
I'll make a release this night

**Comment by dobrodushny** [comment]
@nepalez Cool, thanks) It would be great if you add me as a helper on http://cultofmartians.com/ too :) Also, am I right that readme is need to be updated now?

**Comment by nepalez** [comment]
Done
And back-reference for better craziness http://cultofmartians.com/tasks/adding-binds-to-rspec-sqlimit.html

**Pull request merged**
